namespace SpriteKind {
    export const hoop = SpriteKind.create()
    export const hoopstand = SpriteKind.create()
    export const scoredBall = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    ballSprite = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . 4 4 4 4 . . . . . . 
        . . . . 4 4 4 5 5 4 4 4 . . . . 
        . . . 3 3 3 3 4 4 4 4 4 4 . . . 
        . . 4 3 3 3 3 2 2 2 1 1 4 4 . . 
        . . 3 3 3 3 3 2 2 2 1 1 5 4 . . 
        . 4 3 3 3 3 2 2 2 2 2 5 5 4 4 . 
        . 4 3 3 3 2 2 2 4 4 4 4 5 4 4 . 
        . 4 4 3 3 2 2 4 4 4 4 4 4 4 4 . 
        . 4 2 3 3 2 2 4 4 4 4 4 4 4 4 . 
        . . 4 2 3 3 2 4 4 4 4 4 2 4 . . 
        . . 4 2 2 3 2 2 4 4 4 2 4 4 . . 
        . . . 4 2 2 2 2 2 2 2 2 4 . . . 
        . . . . 4 4 2 2 2 2 4 4 . . . . 
        . . . . . . 4 4 4 4 . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, playerSprite, 0, 0)
    ballSprite.setVelocity(80, -200)
    ballSprite.ay = 500
    ballSprite.z = 1
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.hoop, function (sprite, otherSprite) {
    console.log(sprite.x)
    console.log(otherSprite.x)
    console.log(sprite.y)
    console.log(otherSprite.y)
    if ((sprite.x < otherSprite.x + 3 || sprite.x > otherSprite.x - 13) && sprite.y < otherSprite.y - 11) {
        info.changeScoreBy(1)
        sprite.setPosition(otherSprite.x, sprite.y)
        sprite.setVelocity(0, -100)
    }
    sprite.setKind(SpriteKind.scoredBall)
})
let ballSprite: Sprite = null
let playerSprite: Sprite = null
scene.setBackgroundColor(13)
playerSprite = sprites.create(img`
    . . . . f f f f . . . . 
    . . f f e e e e f f . . 
    . f e e e e e e e f f . 
    f f e f e e e e e e f f 
    f f f e e e e e e e e f 
    f f f e e e e e e f e f 
    f f f f e e e e f f f f 
    f f f f f f f f f f f f 
    f f f f f f f f f f f f 
    . f f f f f f f f f f . 
    . e f f f f f f f f e . 
    e 4 f b b b b b b f 4 e 
    4 d f d d d d d d c d 4 
    4 4 f 6 6 6 6 6 6 f 4 4 
    . . . f f f f f f . . . 
    . . . f f . . f f . . . 
    `, SpriteKind.Player)
controller.moveSprite(playerSprite)
playerSprite.z = 2
playerSprite.setStayInScreen(true)
let chances = 3
let hoopStandSprite = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ........................f.......
    ........................f.......
    ........................f.......
    ..ff.ffffffffffffff.fffff.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    ........................f.......
    .......................fff......
    .....................fffffff....
    ....................fffffffff...
    ...................fffffffffff..
    ..................fffffffffffff.
    `, SpriteKind.hoopstand)
let hoopSprite = sprites.create(img`
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 1 1 1 8 1 1 1 1 1 1 1 8 1 1 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 1 1 1 1 1 1 1 8 1 1 1 1 1 1 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 . . . 8 . . . 8 . . . 8 . . 2 
    2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
    `, SpriteKind.hoop)
hoopStandSprite.z = 3
hoopSprite.z = 4
hoopSprite.setPosition(hoopStandSprite.x - 4, hoopStandSprite.y - 10)
forever(function () {
	
})
